---
- name: Patch OS
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Perform package patches
      ansible.builtin.package:
        update_cache: yes
        name: '*'
        state: latest
        autoremove: yes
