---
- name: Update and Patch Operating System Packages
  hosts: all
  become: true

  tasks:
    - name: Update all packages for Debian/Ubuntu servers
      when: "ansible_distribution" == "Ubuntu"
      ansible.builtin.apt:
        update_cache: yes
        name: "*"
        state: latest
        # Use 'name' to specify packages to exclude, e.g., name: '!apache2'

    - name: Update all packages for RedHat/CentOS servers
      when: "ansible_distribution" == "Ubuntu"
      ansible.builtin.yum:
        name: '*'
        state: latest
        # Use 'exclude' to specify packages to exclude, e.g., exclude: 'kernel*'

