---
- name: Update and Patch Operating System Packages
  hosts: all
  become: true

  tasks:
    - name: Update all packages for Debian/Ubuntu servers
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        # Use 'name' to specify packages to exclude, e.g., name: '!apache2'
      when: ansible_facts['os_family'] == "Debian"

    - name: Update all packages for RedHat/CentOS servers
      ansible.builtin.yum:
        name: '*'
        state: latest
        # Use 'exclude' to specify packages to exclude, e.g., exclude: 'kernel*'
      when: ansible_facts['os_family'] == "RedHat"
