---
- name: Patch OS
  hosts: all
  become: true
  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        update_cache: yes
        name: '*'
        state: latest
        
    - name: Update packages with yum
      when: ansible_pkg_mgr == 'yum'
      yum:
        name: '*'
        state: latest

    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        upgrade: dist

    - name: Upgrade packages with yum
      when: ansible_pkg_mgr == 'yum'
      yum:
        name: '*'
        state: latest
        exclude: kernel*

    - name: Install traceroute package
      when: ansible_pkg_mgr == 'apt'
      apt:
        name: "traceroute"
        state: latest


