---
- name: Update and Patch Operating System Packages
  hosts: all
  become_user: root

  tasks:

    - name: Update apt cache for Debian/Ubuntu servers
      when: ansible_distribution == "Ubuntu"
      become_user: root
      ansible.builtin.apt:
        update_cache: yes


    - name: Upgrade all packages for Debian/Ubuntu servers
      when: ansible_distribution == "Ubuntu"
      become_user: root
      ansible.builtin.apt:
        upgrade: dist


    - name: Update yum cache for RedHat/CentOS servers
      when: ansible_distribution == "Rocky"
      become_user: root
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: yes
        update_only: yes


    - name: Upgrade all packages for RedHat/CentOS servers
      when: ansible_distribution == "Rocky"
      become_user: root
      ansible.builtin.yum:
        name: '*'
        state: latest






