---
- name: Patch OS
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Test privilege escalation
      become: true
      become_method: su
      command: whoami
      register: output

    - debug: var=output.stdout
    
    - name: Perform package patches
      become: true
      become_method: su
      ansible.builtin.package:
        update_cache: yes
        name: '*'
        state: latest
        
    - debug: var=output.stdout


