---
- name: Patch OS
  hosts: all
  become: true
  become_user: root
  become_method: su
  tasks:
    - name: Test privilege escalation
      become: true
      become_method: su
      command: whoami
      register: output

    - debug: var=output.stdout

    - name: update packages using apt
      when: ansible_distribution == "Ubuntu"
      become: true
      become_user: root
      become_method: su
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: yes

    - name: update packages using yum
      when: ansible_distribution == "Rocky"
      become: true
      become_user: root
      become_method: su
      ansible.builtin.dnf:
        name: '*'
        state: latest
