---
- name: Patch OS
  hosts: all
  tasks:
    - name: Test privilege escalation
      become: true
      become_method: su
      command: whoami
      register: output

    - debug: var=output.stdout

- name: Patch debian based servers
  hosts: apt
  tasks:
    - name: Test privilege escalation
      become: yes
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: yes

- name: Patch rhel based servers
  hosts: yum
  tasks:
    - name: Test privilege escalation
      become: yes
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: yes
