---
- name: Patch OS
  hosts: all
  become: true
  become_user: root
  become_method: su
  tasks:
    - name: apt update
      become: true
      become_method: su
      command: sudo apt update
      register: output

    - debug: var=output.stdout

    - name: apt upgrade
      become: true
      become_method: su
      command: sudo apt uprade -y
      register: output

    - debug: var=output.stdout
