---
- name: Patch OS
  hosts: all
  become: true
  become_method: su
  tasks:
    - name: Perform package patches
      become: true
      become_method: su
      ansible.builtin.package:
        update_cache: yes
        name: '*'
        state: latest

